import type { Meta, StoryObj } from '@storybook/react';
import LessonReleaseMenu from './index';

export default {
  title: 'Design System/React UI/Lesson Release Menu',
  component: LessonReleaseMenu
} as Meta<typeof LessonReleaseMenu>;

const template = (args) => (
  <div style={{width: 400}}>
    <LessonReleaseMenu {...args}></LessonReleaseMenu>
  </div>
);

export const Base: StoryObj<typeof LessonReleaseMenu> = {
  args: {
    course: {
      'id': 5,
      'name': 'Scopri il Potere dei Chakra',
      'slug': 'scopri-il-potere-dei-chakra',
      'description': 'Un viaggio attraverso i sette chakra per ritrovare armonia, benessere e connessione interiore. Sblocca l\'energia vitale e risveglia il tuo potenziale.',
      'type': 'scheduled',
      'privacy': '',
      'enforce_lessons_order': false,
      'new_comment_notification_enabled': false,
      'hide_member_count': false,
      'meta_title': '',
      'meta_description': '',
      'og_title': '',
      'og_description': '',
      'og_image': null,
      'sections_order': [8, 9, 10, 11, 12, 13, 14],
      'image_bigger': 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/bigger/scopri-il-potere-dei-chakra_1259.jpg',
      'image_big': 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/big/scopri-il-potere-dei-chakra_5978.jpg',
      'image_medium': 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/medium/scopri-il-potere-dei-chakra_0702.jpg',
      'image_small': 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/small/scopri-il-potere-dei-chakra_4462.jpg',
      'join_status': 'manager',
      'user_completion_rate': 0,
      'created_at': '2025-01-22T08:56:09.941314+01:00',
      'created_by': {
        'id': 9,
        'username': 'team',
        'real_name': '',
        'avatar': 'https://static-cache.quentrix.com/wioggmfc/upfiles/svg/T9.svg',
        'ext_id': null,
        'deleted': false,
        'followings_counter': 0,
        'followers_counter': 5,
        'posts_counter': 12,
        'discussions_counter': 4,
        'polls_counter': 4,
        'categories_counter': 2,
        'date_joined': '2024-04-10T14:37:48.153981+02:00',
        'bio': '',
        'location': '',
        'location_lat_lng': null,
        'position_lat_lng': null,
        'date_of_birth': null,
        'description': '',
        'gender': 'Unspecified',
        'website': '',
        'cover': null,
        'tags': [],
        'reputation': 161,
        'language': 'it',
        'community_badge': true,
        'reg_approved': true,
        'job': 'Barbiere',
        'store': 'Brescia',
        'brand': 'Prima Classe',
        'race': null,
      },
      'categories': [],
      'sections': [{
        'id': 8,
        'name': 'Muladhara: Chakra della Radice',
        'dripped_at': '2025-01-25T15:00:00+01:00',
        'drip_delay': 0,
        'lessons_order': [8],
        'lessons': [{
          'id': 8,
          'name': 'Connettiti alla terra',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 9,
        'name': 'Svadhisthana: Chakra Sacrale',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [9],
        'lessons': [{
          'id': 9,
          'name': 'Flusso creativo e energia delle emozioni',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 10,
        'name': 'Manipura: Chakra del Plesso Solare',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [10],
        'lessons': [{
          'id': 10,
          'name': 'Ritrova fiducia e potere personale',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 11,
        'name': 'Anahata: Chakra del Cuore',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [11],
        'lessons': [{
          'id': 11,
          'name': 'Impara l\u2019amore incondizionato e l\u2019equilibrio',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 12,
        'name': 'Vishuddha: Chakra della Gola',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [12],
        'lessons': [{
          'id': 12,
          'name': 'Esprimi te stesso in modo autentico',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 13,
        'name': 'Ajna: Chakra del Terzo Occhio',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [13],
        'lessons': [{
          'id': 13,
          'name': 'Espandi intuizione e consapevolezza interiore',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 14,
        'name': 'Sahasrara: Chakra della Corona',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [14],
        'lessons': [{
          'id': 14,
          'name': 'Connettiti con l\u2019energia universale',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }],
    },
    section: {
      'id': 8,
      'name': 'Muladhara: Chakra della Radice',
      'dripped_at': '2025-01-25T15:00:00+01:00',
      'drip_delay': 0,
      'lessons_order': [
        8,
      ],
      'lessons': [
        {
          'id': 8,
          'name': 'Connettiti alla terra',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        },
      ],
    },
  },
  render: template,
};
