/**
 * DEFAULT CONF VALIDATION OPTION
 */
export const FEATURES_OPTION = 'features';
export const DEFAULT_FEATURES_OPTION = [];

/** FEATURES */
export const INTERESTS = 'interests';
export const CUSTOMIZE = 'customize';
export const ADDONS = 'addons';
export const DOMAIN = 'domain';
export const SOCIAL_PROVIDERS = 'social_providers';
export const COMMUNITY_SUBSCRIPTION = 'community_subscription';
export const SEO = 'seo';
export const ADVERTISING = 'advertising';
export const GOOGLE_CLOUD_API = 'google_cloud_api';
export const HOTJAR = 'hotjar';
export const SQREEN = 'sqreen';
export const INCUBATORS = 'incubators';
export const CMS = 'cms';
export const LEGAL_PAGES = 'legal_pages';
export const SCORING = 'scoring';
export const USER_ROLES = 'user_roles';
export const EMAIL_MANAGER = 'email_manager';
export const LOYALTY = 'loyalty';
export const BROADCAST = 'broadcast';
export const INVITATION = 'invitation';
export const APP_SETTINGS = 'app_settings';
export const MODERATION_FLAGS = 'moderation_flags';
export const MODERATION_CONTENTS = 'moderation_contents';
export const MODERATION_USERS_BLOCKED = 'moderation_users_blocked';
export const MODERATION_USERS = 'moderation_users';
export const DATA_PROVISIONING_DASHBOARD = 'data_provisioning_dashboard';
export const DATA_PROVISIONING_USERS = 'data_provisioning_users';
export const DATA_PROVISIONING_CONTENTS = 'data_provisioning_contents';
export const DATA_PROVISIONING_INTERESTS = 'data_provisioning_interests';
export const DATA_PROVISIONING_POLLS = 'data_provisioning_polls';
export const DATA_PROVISIONING_REPORTS = 'data_provisioning_reports';
export const REGISTRATION_ALERTS = 'registration_alerts';
export const SOCIAL_SHARE = 'social_share';
export const FEED_SETTINGS = 'stream_settings';
export const TAGGING = 'tagging';
export const API_V2 = 'api_v2';
export const WEBHOOK = 'webhook';
export const HEADLESS = 'headless';
export const CUSTOMIZE_HEADLESS = 'customize_headless';
export const SYSTEM_PAGES = 'system_pages';
export const REACTION = 'reaction';
export const PRIVATE_MESSAGES = 'private_messages';
