export const PREFIX = 'SCComposer';

export const DEFAULT_INITIAL_MAX_HEIGHT_CONTENT_EDITOR = 370;
export const DEFAULT_EXTRA_SPACE_CONTENT_EDITOR = 210;
export const DEFAULT_HEIGHT_SWITCH_CONTENT_TYPE = 45;
