export const prefetchedCourses = [
  {
    id: 1,
    name: 'Distributed multi-state capability',
    slug: 'distributed-multi-state-capability',
    type: 'structured',
    privacy: 'open',
    image_bigger: 'https://static-cache.quentrix.com/wioggmfc/upfiles/structureds/bigger/distributed-multi-state-capability_3372.jpg',
    image_big: 'https://static-cache.quentrix.com/wioggmfc/upfiles/structureds/big/distributed-multi-state-capability_0486.jpg',
    image_medium: 'https://static-cache.quentrix.com/wioggmfc/upfiles/structureds/medium/distributed-multi-state-capability_5903.jpg',
    image_small: 'https://static-cache.quentrix.com/wioggmfc/upfiles/structureds/small/distributed-multi-state-capability_6812.jpg',
    join_status: 'manager',
    created_at: '2025-01-16T14:52:24.400913+01:00',
    created_by: {
      id: 9,
      username: 'team',
      real_name: '',
      avatar: 'https://static-cache.quentrix.com/wioggmfc/upfiles/svg/T9.svg',
      ext_id: null,
      deleted: false,
      followings_counter: 0,
      followers_counter: 5,
      posts_counter: 12,
      discussions_counter: 4,
      polls_counter: 4,
      categories_counter: 2,
      date_joined: '2024-04-10T14:37:48.153981+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 159,
      language: 'it',
      community_badge: true,
      reg_approved: true,
      job: 'Barbiere',
      store: 'Brescia',
      brand: 'Prima Classe',
      race: null
    },
    categories: [
      {
        id: 1,
        tags: [],
        followed: true,
        order: 14,
        name: 'Band preferite',
        name_synonyms: '',
        slug: 'band-preferite',
        slogan:
          "Note che si trasformano in emozioni: condividi la tua passione musicale, esplorando insieme le band preferite che ti fanno vibrare l'anima.",
        html_info: null,
        seo_title: '',
        seo_description: '',
        auto_follow: 'none',
        active: true,
        image_original: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/original/band-preferite_4420.png',
        image_bigger: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/bigger/band-preferite_8770.png',
        image_big: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/big/band-preferite_7524.png',
        image_medium: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/medium/band-preferite_8937.png',
        image_small: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/small/band-preferite_3325.png',
        emotional_image_original: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/e_original/band-preferite_4837.png',
        emotional_image_position: 50,
        stream_order_by: 'recent',
        followers_counter: 315
      }
    ]
  },
  {
    id: 2,
    name: 'Pre-emptive fresh-thinking frame',
    slug: 'pre-emptive-fresh-thinking-frame',
    type: 'scheduled',
    privacy: 'open',
    image_bigger: 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/bigger/pre-emptive-fresh-thinking-frame_1155.jpg',
    image_big: 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/big/pre-emptive-fresh-thinking-frame_2446.jpg',
    image_medium: 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/medium/pre-emptive-fresh-thinking-frame_3088.jpg',
    image_small: 'https://static-cache.quentrix.com/wioggmfc/upfiles/scheduleds/small/pre-emptive-fresh-thinking-frame_3209.jpg',
    join_status: 'joined',
    created_at: '2025-01-20T12:38:43.200219+01:00',
    created_by: {
      id: 1,
      username: 'admin',
      real_name: 'Amministratore',
      avatar: 'https://static-cache.quentrix.com/wioggmfc/upfiles/avatars/1/resized/209/209/28b02add2c23b3a71801734eba773592.png',
      ext_id: null,
      deleted: false,
      followings_counter: 1,
      followers_counter: 4,
      posts_counter: 614,
      discussions_counter: 551,
      polls_counter: 84,
      categories_counter: 5,
      date_joined: '2024-04-10T13:23:59.754335+02:00',
      bio: 'Vidi, feci, raccontai e poi me ne andai',
      location: 'Milano',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: '1973-07-09',
      description: 'Avvocato Civilista',
      gender: 'Unspecified',
      website: 'https://selfcommunity.com/',
      cover: 'https://static-cache.quentrix.com/wioggmfc/upfiles/user_media/admin/cover/55655364-f786-4ead-a97f-56b1770ad951.jpg',
      tags: [
        {
          id: 93,
          type: 'user',
          name: 'PINO',
          description: '',
          color: '#e57373',
          visible: true,
          visibility_boost: false,
          active: true,
          deleted: false,
          created_at: '2024-05-31T16:15:43.986224+02:00'
        }
      ],
      reputation: 2748,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: 'JR Clinic Manager',
      store: 'Erbusco',
      brand: 'Il Barbiere',
      race: 'Umano'
    },
    categories: [
      {
        id: 1,
        tags: [],
        followed: true,
        order: 14,
        name: 'Band preferite',
        name_synonyms: '',
        slug: 'band-preferite',
        slogan:
          "Note che si trasformano in emozioni: condividi la tua passione musicale, esplorando insieme le band preferite che ti fanno vibrare l'anima.",
        html_info: null,
        seo_title: '',
        seo_description: '',
        auto_follow: 'none',
        active: true,
        image_original: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/original/band-preferite_4420.png',
        image_bigger: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/bigger/band-preferite_8770.png',
        image_big: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/big/band-preferite_7524.png',
        image_medium: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/medium/band-preferite_8937.png',
        image_small: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/small/band-preferite_3325.png',
        emotional_image_original: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/e_original/band-preferite_4837.png',
        emotional_image_position: 50,
        stream_order_by: 'recent',
        followers_counter: 315
      },
      {
        id: 2,
        tags: [],
        followed: true,
        order: 13,
        name: 'Nuovi generi musicali alternativi',
        name_synonyms: '#alternative',
        slug: 'nuovi-generi-musicali',
        slogan:
          "Esplora l'innovazione sonora e scopri nuovi ritmi inaspettati. Abbraccia l'originalità dei nuovi generi musicali alternativi e lasciati trasportare dalle vibrazioni uniche.",
        html_info: null,
        seo_title: '',
        seo_description: '',
        auto_follow: 'forced',
        active: true,
        image_original: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/original/nuovi-generi-musicali_5714.png',
        image_bigger: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/bigger/nuovi-generi-musicali_8854.png',
        image_big: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/big/nuovi-generi-musicali_0593.png',
        image_medium: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/medium/nuovi-generi-musicali_0368.png',
        image_small: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/small/nuovi-generi-musicali_7491.png',
        emotional_image_original: 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/e_original/nuovi-generi-musicali_7739.png',
        emotional_image_position: 50,
        stream_order_by: 'recent',
        followers_counter: 345
      }
    ]
  }
];
