const prefetchedEvents = [
  {
    id: 105,
    name: 'Evento di prova',
    description: 'Questo è un evento di prova',
    slug: 'evento-di-prova',
    color: '#DBDBDB',
    privacy: 'public',
    visible: true,
    active: true,
    show_on_feed: false,
    subscription_status: null,
    image_bigger: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/bigger/evento-di-prova_6850.jpg',
    image_big: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/big/evento-di-prova_0152.jpg',
    image_medium: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/medium/evento-di-prova_3635.jpg',
    image_small: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/small/evento-di-prova_6424.jpg',
    subscribers_counter: 1,
    goings_counter: 0,
    start_date: '2024-08-13T16:00:00+02:00',
    end_date: '2024-08-13T17:00:00+02:00',
    recurring: 'never',
    location: 'virtual',
    geolocation: null,
    geolocation_lat: null,
    geolocation_lng: null,
    link: 'https://www.youtube.com/?app=desktop&hl=it',
    created_at: '2024-08-08T10:26:36.309587+02:00',
    created_by: {
      id: 1,
      username: 'admin',
      real_name: '',
      avatar: 'https://internal.stage.quentrix.com/wioggmfc/avatar/admin',
      ext_id: null,
      deleted: false,
      followings_counter: 1,
      followers_counter: 1,
      posts_counter: 4,
      discussions_counter: 0,
      polls_counter: 0,
      categories_counter: 6,
      date_joined: '2024-04-10T13:23:59.754335+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 75,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: 'Commessa Adv',
      store: 'Erbusco',
      brand: 'Sede'
    },
    managed_by: {
      id: 1,
      username: 'admin',
      real_name: '',
      avatar: 'https://internal.stage.quentrix.com/wioggmfc/avatar/admin',
      ext_id: null,
      deleted: false,
      followings_counter: 1,
      followers_counter: 1,
      posts_counter: 4,
      discussions_counter: 0,
      polls_counter: 0,
      categories_counter: 6,
      date_joined: '2024-04-10T13:23:59.754335+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 75,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: 'Commessa Adv',
      store: 'Erbusco',
      brand: 'Sede'
    }
  },
  {
    id: 107,
    name: 'Evento di persona',
    description: 'Questo è un evento di persona',
    slug: 'evento-di-persona',
    color: '#DBDBDB',
    privacy: 'public',
    visible: true,
    active: true,
    show_on_feed: false,
    subscription_status: null,
    image_bigger: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/bigger/evento-di-persona_1481.jpg',
    image_big: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/big/evento-di-persona_6521.jpg',
    image_medium: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/medium/evento-di-persona_4765.jpg',
    image_small: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/small/evento-di-persona_4536.jpg',
    subscribers_counter: 1,
    goings_counter: 0,
    start_date: '2024-08-09T17:00:00+02:00',
    end_date: null,
    recurring: 'never',
    location: 'in person',
    geolocation: 'P.za del Duomo, 20122 Milano MI, Italia',
    geolocation_lat: 45.4640976,
    geolocation_lng: 9.1919265,
    link: null,
    created_at: '2024-08-08T10:51:50.692540+02:00',
    created_by: {
      id: 1,
      username: 'admin',
      real_name: '',
      avatar: 'https://internal.stage.quentrix.com/wioggmfc/avatar/admin',
      ext_id: null,
      deleted: false,
      followings_counter: 1,
      followers_counter: 1,
      posts_counter: 4,
      discussions_counter: 0,
      polls_counter: 0,
      categories_counter: 6,
      date_joined: '2024-04-10T13:23:59.754335+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 75,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: 'Commessa Adv',
      store: 'Erbusco',
      brand: 'Sede'
    },
    managed_by: {
      id: 1,
      username: 'admin',
      real_name: '',
      avatar: 'https://internal.stage.quentrix.com/wioggmfc/avatar/admin',
      ext_id: null,
      deleted: false,
      followings_counter: 1,
      followers_counter: 1,
      posts_counter: 4,
      discussions_counter: 0,
      polls_counter: 0,
      categories_counter: 6,
      date_joined: '2024-04-10T13:23:59.754335+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 75,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: 'Commessa Adv',
      store: 'Erbusco',
      brand: 'Sede'
    }
  },
  {
    id: 111,
    name: 'Tour Cagliari',
    description: '',
    slug: 'tour-cagliari',
    color: '#DBDBDB',
    privacy: 'public',
    visible: true,
    active: true,
    show_on_feed: true,
    subscription_status: 'subscribed',
    image_bigger: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/bigger/tour-cagliari_4613.jpg',
    image_big: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/big/tour-cagliari_5634.jpg',
    image_medium: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/medium/tour-cagliari_6311.jpg',
    image_small: 'https://static.stage.quentrix.com/wioggmfc/upfiles/events/small/tour-cagliari_3043.jpg',
    subscribers_counter: 1,
    goings_counter: 0,
    start_date: '2024-08-11T09:15:00+02:00',
    end_date: null,
    recurring: 'never',
    location: 'in person',
    geolocation: 'Piazza Costituzione, Cagliari CA, Italy',
    geolocation_lat: 39.2153291,
    geolocation_lng: 9.1171268,
    link: null,
    created_at: '2024-08-08T11:33:33.586626+02:00',
    created_by: {
      id: 642,
      username: 'simonester',
      real_name: '',
      avatar: 'https://static.stage.quentrix.com/wioggmfc/upfiles/avatars/642/resized/209/209/56ca76ca6a31a337972026011f597cec.png',
      ext_id: null,
      deleted: false,
      followings_counter: 0,
      followers_counter: 0,
      posts_counter: 14,
      discussions_counter: 1,
      polls_counter: 0,
      categories_counter: 6,
      date_joined: '2024-07-08T10:59:03.296820+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 52,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: null,
      store: 'Cagliari',
      brand: null
    },
    managed_by: {
      id: 642,
      username: 'simonester',
      real_name: '',
      avatar: 'https://static.stage.quentrix.com/wioggmfc/upfiles/avatars/642/resized/209/209/56ca76ca6a31a337972026011f597cec.png',
      ext_id: null,
      deleted: false,
      followings_counter: 0,
      followers_counter: 0,
      posts_counter: 14,
      discussions_counter: 1,
      polls_counter: 0,
      categories_counter: 6,
      date_joined: '2024-07-08T10:59:03.296820+02:00',
      bio: '',
      location: '',
      location_lat_lng: null,
      position_lat_lng: null,
      date_of_birth: null,
      description: '',
      gender: 'Unspecified',
      website: '',
      cover: null,
      tags: [],
      reputation: 52,
      language: 'it',
      community_badge: false,
      reg_approved: true,
      job: null,
      store: 'Cagliari',
      brand: null
    }
  }
];
