import ContributionFollowNotificationToast, {NotificationContributionFollowToastProps} from './ContributionFollow';
export default ContributionFollowNotificationToast;
export {NotificationContributionFollowToastProps};
