import type { Meta, StoryObj } from '@storybook/react';
import CourseForm, { CourseFormProps } from './index';
import { SCCourseFormStepType } from './CourseForm';
import { SCCourseJoinStatusType, SCCoursePrivacyType, SCCourseTypologyType, SCLanguageType } from '@selfcommunity/types';

export default {
  title: 'Design System/React UI/Course Form',
  component: CourseForm,
} as Meta<typeof CourseForm>;

const template = (args) => (
  <div style={{width: 800}}>
    <CourseForm {...args} />
  </div>
);


export const Base: StoryObj<CourseFormProps> = {
  args: {},
  render: template
};

export const EditForm: StoryObj<typeof CourseForm> = {
  args: {
    step: SCCourseFormStepType.CUSTOMIZATION,
    course: {
      'id': 1,
      'name': 'Scopri il Potere dei Chakra',
      'slug': 'scopri-il-potere-dei-chakra',
      'description': 'Esplora i 7 chakra, riequilibra energia e armonia interiore con tecniche pratiche.',
      'type': SCCourseTypologyType.SELF,
      'privacy': SCCoursePrivacyType.DRAFT,
      'enforce_lessons_order': false,
      'new_comment_notification_enabled': false,
      'hide_member_count': false,
      'meta_title': '',
      'meta_description': '',
      'og_title': '',
      'og_description': '',
      'og_image': undefined,
      'sections_order': [1, 2, 3, 4, 5, 6, 7],
      'image_bigger': 'https://static-cache.quentrix.com/wioggmfc/upfiles/courses/bigger/scopri-il-potere-dei-chakra_4005.jpg',
      'image_big': 'https://static-cache.quentrix.com/wioggmfc/upfiles/courses/big/scopri-il-potere-dei-chakra_6270.jpg',
      'image_medium': 'https://static-cache.quentrix.com/wioggmfc/upfiles/courses/medium/scopri-il-potere-dei-chakra_7661.jpg',
      'image_small': 'https://static-cache.quentrix.com/wioggmfc/upfiles/courses/small/scopri-il-potere-dei-chakra_3092.jpg',
      'join_status': SCCourseJoinStatusType.CREATOR,
      'user_completion_rate': 0,
      'created_at': '2025-01-24T12:32:32.087623+01:00',
      'created_by': {
        'id': 9,
        'username': 'team',
        'real_name': '',
        'avatar': 'https://static-cache.quentrix.com/wioggmfc/upfiles/svg/T9.svg',
        'ext_id': undefined,
        'deleted': false,
        'followings_counter': 0,
        'followers_counter': 5,
        'posts_counter': 12,
        'discussions_counter': 4,
        'polls_counter': 4,
        'categories_counter': 2,
        'date_joined': new Date('2024-04-10T14:37:48.153981+02:00'),
        'bio': '',
        'location': '',
        'location_lat_lng': undefined,
        'position_lat_lng': undefined,
        'date_of_birth': undefined,
        'description': '',
        'gender': 'Unspecified',
        'website': '',
        'cover': undefined,
        'tags': [],
        'reputation': 163,
        'language': SCLanguageType.IT,
        'community_badge': true,
        'reg_approved': true,
        'job': 'Barbiere',
        'store': 'Brescia',
        'brand': 'Prima Classe',
        'race': null,
      },
      'categories': [{
        'id': 14,
        'tags': [],
        'followed': false,
        'order': 1,
        'name': 'Tradizioni e Territorio',
        'name_synonyms': '',
        'slug': 'tradizioni-e-territorio',
        'slogan': 'Esplora le radici della nostra terra e scopri le tradizioni che la rendono unica, un viaggio nel cuore dell\'Italia tramite storie antiche e territori da sogno.',
        'html_info': undefined,
        'seo_title': '',
        'seo_description': '',
        'auto_follow': 'none',
        'active': true,
        'image_original': 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/original/tradizioni-e-territorio_5833.png',
        'image_bigger': 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/bigger/tradizioni-e-territorio_9179.png',
        'image_big': 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/big/tradizioni-e-territorio_6404.png',
        'image_medium': 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/medium/tradizioni-e-territorio_7584.png',
        'image_small': 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/small/tradizioni-e-territorio_1924.png',
        'emotional_image_original': 'https://static-cache.quentrix.com/wioggmfc/upfiles/categories/e_original/tradizioni-e-territorio_0050.png',
        'emotional_image_position': 50,
        'stream_order_by': 'recent',
        'followers_counter': 11,
      }],
      'sections': [{
        'id': 1,
        'name': 'Muladhara - Chakra della Radice',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [1, 8, 9, 10, 11, 12],
        'lessons': [{
          'id': 1,
          'course_id': 1,
          'section_id': 1,
          'name': 'Muladhara - Intro',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 8,
          'course_id': 1,
          'section_id': 1,
          'name': 'Muladhara - Le Radici della Stabilit\u00e0',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 9,
          'course_id': 1,
          'section_id': 1,
          'name': 'Muladhara - Pratiche di Radicamento',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 10,
          'course_id': 1,
          'section_id': 1,
          'name': 'Muladhara - Energia Vitale e Sopravvivenza',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 11,
          'course_id': 1,
          'section_id': 1,
          'name': 'Muladhara - Il Ruolo della Terra nel Radicamento',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 12,
          'course_id': 1,
          'section_id': 1,
          'name': 'Muladhara - Pietra e Mantra',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 2,
        'name': 'Svadhisthana - Chakra Sacrale',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [2, 13, 14, 15],
        'lessons': [{
          'id': 2,
          'course_id': 1,
          'section_id': 2,
          'name': 'Svadhisthana - Intro',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 13,
          'course_id': 1,
          'section_id': 2,
          'name': 'Svadhisthana - Emozioni e Relazioni',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 14,
          'course_id': 1,
          'section_id': 2,
          'name': 'Svadhisthana - Il Corpo e il Piacere',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 15,
          'course_id': 1,
          'section_id': 2,
          'name': 'Svadhisthana - Pietre e Mantra',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 3,
        'name': 'Manipura - Chakra del Plesso Solare',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [3, 16],
        'lessons': [{
          'id': 3,
          'course_id': 1,
          'section_id': 3,
          'name': 'Manipura - Intro',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 16,
          'course_id': 1,
          'section_id': 3,
          'name': 'Manipura - Pietra, Mantra e Altri Temi',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 4,
        'name': 'Anahata - Chakra del Cuore',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [4, 17],
        'lessons': [{
          'id': 4,
          'course_id': 1,
          'section_id': 4,
          'name': 'Anahata - Intro',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 17,
          'course_id': 1,
          'section_id': 4,
          'name': 'Anahata - Il Potere dell\'Amore Incondizionato',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 5,
        'name': 'Vishuddha - Chakra della Gola',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [5, 18],
        'lessons': [{
          'id': 5,
          'course_id': 1,
          'section_id': 5,
          'name': 'Vishuddha - Intro',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 18,
          'course_id': 1,
          'section_id': 5,
          'name': 'Vishuddha - Comunicare con Autenticit\u00e0',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 6,
        'name': 'Ajna - Chakra del Terzo Occhio',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [6, 19],
        'lessons': [{
          'id': 6,
          'course_id': 1,
          'section_id': 6,
          'name': 'Ajna - Intro',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 19,
          'course_id': 1,
          'section_id': 6,
          'name': 'Ajna - Intuizione e Visione Interiore',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }, {
        'id': 7,
        'name': 'Sahasrara - Chakra della Corona',
        'dripped_at': null,
        'drip_delay': 0,
        'lessons_order': [7, 20],
        'lessons': [{
          'id': 7,
          'course_id': 1,
          'section_id': 7,
          'name': 'Sahasrara - Intro - Chakra della Corona',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }, {
          'id': 20,
          'course_id': 1,
          'section_id': 7,
          'name': 'Sahasrara - Connessione con l\'Universo',
          'type': 'lesson',
          'status': 'draft',
          'comments_enabled': true,
        }],
      }],
    },
  },
  render: template,
};