export const COMPOSER_TYPE_DISCUSSION = 'discussion';
export const COMPOSER_TYPE_POST = 'post';
export const COMPOSER_TYPE_POLL = 'poll';
export const COMPOSER_TYPES = {
  [COMPOSER_TYPE_DISCUSSION]: COMPOSER_TYPE_DISCUSSION,
  [COMPOSER_TYPE_POST]: COMPOSER_TYPE_POST,
  [COMPOSER_TYPE_POLL]: COMPOSER_TYPE_POLL
};

export const COMPOSER_TITLE_MAX_LENGTH = 160;
export const COMPOSER_POLL_TITLE_MAX_LENGTH = 160;
export const COMPOSER_POLL_MIN_CHOICES = 2;
export const COMPOSER_POLL_MIN_CLOSE_DATE_DELTA = 2;
