import {SCCountryType} from '@selfcommunity/types/src/types';

export enum COUNTRY_CODES {
  IT = 'IT'
}

export const countries: readonly SCCountryType[] = [
  {code: 'AD', label: 'Andorra', phone: '376', taxType: 'ad_nrt'},
  {code: 'AE', label: 'United Arab Emirates', phone: '971', taxType: 'ae_trn'},
  {code: 'AF', label: 'Afghanistan', phone: '93', taxType: 'unknown'},
  {code: 'AG', label: 'Antigua and Barbuda', phone: '1-268', taxType: 'unknown'},
  {code: 'AI', label: 'Anguilla', phone: '1-264', taxType: 'unknown'},
  {code: 'AL', label: 'Albania', phone: '355', taxType: 'unknown'},
  {code: 'AM', label: 'Armenia', phone: '374', taxType: 'unknown'},
  {code: 'AO', label: 'Angola', phone: '244', taxType: 'unknown'},
  {code: 'AQ', label: 'Antarctica', phone: '672', taxType: 'unknown'},
  {code: 'AR', label: 'Argentina', phone: '54', taxType: 'ar_cuit'},
  {code: 'AS', label: 'American Samoa', phone: '1-684', taxType: 'unknown'},
  {code: 'AT', label: 'Austria', phone: '43', taxType: 'eu_vat'},
  {code: 'AU', label: 'Australia', phone: '61', taxType: 'au_abn'},
  {code: 'AW', label: 'Aruba', phone: '297', taxType: 'unknown'},
  {code: 'AX', label: 'Alland Islands', phone: '358', taxType: 'unknown'},
  {code: 'AZ', label: 'Azerbaijan', phone: '994', taxType: 'unknown'},
  {code: 'BA', label: 'Bosnia and Herzegovina', phone: '387', taxType: 'unknown'},
  {code: 'BB', label: 'Barbados', phone: '1-246', taxType: 'unknown'},
  {code: 'BD', label: 'Bangladesh', phone: '880', taxType: 'unknown'},
  {code: 'BE', label: 'Belgium', phone: '32', taxType: 'eu_vat'},
  {code: 'BF', label: 'Burkina Faso', phone: '226', taxType: 'unknown'},
  {code: 'BG', label: 'Bulgaria', phone: '359', taxType: 'eu_vat'},
  {code: 'BH', label: 'Bahrain', phone: '973', taxType: 'unknown'},
  {code: 'BI', label: 'Burundi', phone: '257', taxType: 'unknown'},
  {code: 'BJ', label: 'Benin', phone: '229', taxType: 'unknown'},
  {code: 'BL', label: 'Saint Barthelemy', phone: '590', taxType: 'unknown'},
  {code: 'BM', label: 'Bermuda', phone: '1-441', taxType: 'unknown'},
  {code: 'BN', label: 'Brunei Darussalam', phone: '673', taxType: 'unknown'},
  {code: 'BO', label: 'Bolivia', phone: '591', taxType: 'bo_tin'},
  {code: 'BR', label: 'Brazil', phone: '55', taxType: 'br_cnpj'},
  {code: 'BS', label: 'Bahamas', phone: '1-242', taxType: 'unknown'},
  {code: 'BT', label: 'Bhutan', phone: '975', taxType: 'unknown'},
  {code: 'BV', label: 'Bouvet Island', phone: '47', taxType: 'unknown'},
  {code: 'BW', label: 'Botswana', phone: '267', taxType: 'unknown'},
  {code: 'BY', label: 'Belarus', phone: '375', taxType: 'by_unp'},
  {code: 'BZ', label: 'Belize', phone: '501', taxType: 'unknown'},
  {code: 'CA', label: 'Canada', phone: '1', taxType: 'ca_bn'},
  {code: 'CC', label: 'Cocos (Keeling) Islands', phone: '61', taxType: 'unknown'},
  {code: 'CD', label: 'Congo, Democratic Republic of the', phone: '243', taxType: 'unknown'},
  {code: 'CF', label: 'Central African Republic', phone: '236', taxType: 'unknown'},
  {code: 'CG', label: 'Congo, Republic of the', phone: '242', taxType: 'unknown'},
  {code: 'CH', label: 'Switzerland', phone: '41', taxType: 'ch_vat'},
  {code: 'CI', label: "Cote d'Ivoire", phone: '225', taxType: 'unknown'},
  {code: 'CK', label: 'Cook Islands', phone: '682', taxType: 'unknown'},
  {code: 'CL', label: 'Chile', phone: '56', taxType: 'cl_tin'},
  {code: 'CM', label: 'Cameroon', phone: '237', taxType: 'unknown'},
  {code: 'CN', label: 'China', phone: '86', taxType: 'cn_tin'},
  {code: 'CO', label: 'Colombia', phone: '57', taxType: 'co_nit'},
  {code: 'CR', label: 'Costa Rica', phone: '506', taxType: 'ct_tin'},
  {code: 'CU', label: 'Cuba', phone: '53', taxType: 'unknown'},
  {code: 'CV', label: 'Cape Verde', phone: '238', taxType: 'unknown'},
  {code: 'CW', label: 'Curacao', phone: '599', taxType: 'unknown'},
  {code: 'CX', label: 'Christmas Island', phone: '61', taxType: 'unknown'},
  {code: 'CY', label: 'Cyprus', phone: '357', taxType: 'eu_vat'},
  {code: 'CZ', label: 'Czech Republic', phone: '420', taxType: 'eu_vat'},
  {code: 'DE', label: 'Germany', phone: '49', taxType: 'eu_vat'},
  {code: 'DJ', label: 'Djibouti', phone: '253', taxType: 'unknown'},
  {code: 'DK', label: 'Denmark', phone: '45', taxType: 'eu_vat'},
  {code: 'DM', label: 'Dominica', phone: '1-767', taxType: 'unknown'},
  {code: 'DO', label: 'Dominican Republic', phone: '1-809', taxType: 'do_rcn'},
  {code: 'DZ', label: 'Algeria', phone: '213', taxType: 'unknown'},
  {code: 'EC', label: 'Ecuador', phone: '593', taxType: 'ec_ruc'},
  {code: 'EE', label: 'Estonia', phone: '372', taxType: 'eu_vat'},
  {code: 'EG', label: 'Egypt', phone: '20', taxType: 'eg_tin'},
  {code: 'EH', label: 'Western Sahara', phone: '212', taxType: 'unknown'},
  {code: 'ER', label: 'Eritrea', phone: '291', taxType: 'unknown'},
  {code: 'ES', label: 'Spain', phone: '34', taxType: 'es_cif'},
  {code: 'ET', label: 'Ethiopia', phone: '251', taxType: 'unknown'},
  {code: 'FI', label: 'Finland', phone: '358', taxType: 'eu_vat'},
  {code: 'FJ', label: 'Fiji', phone: '679', taxType: 'unknown'},
  {code: 'FK', label: 'Falkland Islands (Malvinas)', phone: '500', taxType: 'unknown'},
  {code: 'FM', label: 'Micronesia, Federated States of', phone: '691', taxType: 'unknown'},
  {code: 'FO', label: 'Faroe Islands', phone: '298', taxType: 'unknown'},
  {
    code: 'FR',
    label: 'France',
    phone: '33',
    taxType: 'eu_vat',
    taxRateId: 'txr_1OuCViBbviITO61LcJRQ3Pcg',
    taxRatePercentage: 0.13
  },
  {code: 'GA', label: 'Gabon', phone: '241', taxType: 'unknown'},
  {code: 'GB', label: 'United Kingdom', phone: '44', taxType: 'gb_vat'},
  {code: 'GD', label: 'Grenada', phone: '1-473', taxType: 'unknown'},
  {code: 'GE', label: 'Georgia', phone: '995', taxType: 'ge_vat'},
  {code: 'GF', label: 'French Guiana', phone: '594', taxType: 'unknown'},
  {code: 'GG', label: 'Guernsey', phone: '44', taxType: 'unknown'},
  {code: 'GH', label: 'Ghana', phone: '233', taxType: 'unknown'},
  {code: 'GI', label: 'Gibraltar', phone: '350', taxType: 'unknown'},
  {code: 'GL', label: 'Greenland', phone: '299', taxType: 'unknown'},
  {code: 'GM', label: 'Gambia', phone: '220', taxType: 'unknown'},
  {code: 'GN', label: 'Guinea', phone: '224', taxType: 'unknown'},
  {code: 'GP', label: 'Guadeloupe', phone: '590', taxType: 'unknown'},
  {code: 'GQ', label: 'Equatorial Guinea', phone: '240', taxType: 'unknown'},
  {code: 'GR', label: 'Greece', phone: '30', taxType: 'eu_vat'},
  {code: 'GS', label: 'South Georgia and the South Sandwich Islands', phone: '500', taxType: 'unknown'},
  {code: 'GT', label: 'Guatemala', phone: '502', taxType: 'unknown'},
  {code: 'GU', label: 'Guam', phone: '1-671', taxType: 'unknown'},
  {code: 'GW', label: 'Guinea-Bissau', phone: '245', taxType: 'unknown'},
  {code: 'GY', label: 'Guyana', phone: '592', taxType: 'unknown'},
  {code: 'HK', label: 'Hong Kong', phone: '852', taxType: 'hk_br'},
  {code: 'HM', label: 'Heard Island and McDonald Islands', phone: '672', taxType: 'unknown'},
  {code: 'HN', label: 'Honduras', phone: '504', taxType: 'unknown'},
  {code: 'HR', label: 'Croatia', phone: '385', taxType: 'eu_vat'},
  {code: 'HT', label: 'Haiti', phone: '509', taxType: 'unknown'},
  {code: 'HU', label: 'Hungary', phone: '36', taxType: 'eu_vat'},
  {code: 'ID', label: 'Indonesia', phone: '62', taxType: 'id_npwp'},
  {code: 'IE', label: 'Ireland', phone: '353', taxType: 'eu_vat'},
  {code: 'IL', label: 'Israel', phone: '972', taxType: 'il_vat'},
  {code: 'IM', label: 'Isle of Man', phone: '44', taxType: 'unknown'},
  {code: 'IN', label: 'India', phone: '91', taxType: 'in_gst'},
  {code: 'IO', label: 'British Indian Ocean Territory', phone: '246', taxType: 'unknown'},
  {code: 'IQ', label: 'Iraq', phone: '964', taxType: 'unknown'},
  {code: 'IR', label: 'Iran, Islamic Republic of', phone: '98', taxType: 'unknown'},
  {code: 'IS', label: 'Iceland', phone: '354', taxType: 'is_vat'},
  {
    code: 'IT',
    label: 'Italy',
    phone: '39',
    taxType: 'eu_vat',
    taxRateId: 'txr_1OuCV6BbviITO61LXb1Vwpez',
    taxRatePercentage: 0.22
  },
  {code: 'JE', label: 'Jersey', phone: '44', taxType: 'unknown'},
  {code: 'JM', label: 'Jamaica', phone: '1-876', taxType: 'unknown'},
  {code: 'JO', label: 'Jordan', phone: '962', taxType: 'unknown'},
  {code: 'JP', label: 'Japan', phone: '81', taxType: 'jp_cn'},
  {code: 'KE', label: 'Kenya', phone: '254', taxType: 'ke_pin'},
  {code: 'KG', label: 'Kyrgyzstan', phone: '996', taxType: 'unknown'},
  {code: 'KH', label: 'Cambodia', phone: '855', taxType: 'unknown'},
  {code: 'KI', label: 'Kiribati', phone: '686', taxType: 'unknown'},
  {code: 'KM', label: 'Comoros', phone: '269', taxType: 'unknown'},
  {code: 'KN', label: 'Saint Kitts and Nevis', phone: '1-869', taxType: 'unknown'},
  {code: 'KP', label: "Korea, Democratic People's Republic of", phone: '850', taxType: 'unknown'},
  {code: 'KR', label: 'Korea, Republic of', phone: '82', taxType: 'kr_brn'},
  {code: 'KW', label: 'Kuwait', phone: '965', taxType: 'unknown'},
  {code: 'KY', label: 'Cayman Islands', phone: '1-345', taxType: 'unknown'},
  {code: 'KZ', label: 'Kazakhstan', phone: '7', taxType: 'unknown'},
  {code: 'LA', label: "Lao People's Democratic Republic", phone: '856', taxType: 'unknown'},
  {code: 'LB', label: 'Lebanon', phone: '961', taxType: 'unknown'},
  {code: 'LC', label: 'Saint Lucia', phone: '1-758', taxType: 'unknown'},
  {code: 'LI', label: 'Liechtenstein', phone: '423', taxType: 'li_uid'},
  {code: 'LK', label: 'Sri Lanka', phone: '94', taxType: 'unknown'},
  {code: 'LR', label: 'Liberia', phone: '231', taxType: 'unknown'},
  {code: 'LS', label: 'Lesotho', phone: '266', taxType: 'unknown'},
  {code: 'LT', label: 'Lithuania', phone: '370', taxType: 'eu_vat'},
  {code: 'LU', label: 'Luxembourg', phone: '352', taxType: 'lu_vat'},
  {code: 'LV', label: 'Latvia', phone: '371', taxType: 'lv_vat'},
  {code: 'LY', label: 'Libya', phone: '218', taxType: 'unknown'},
  {code: 'MA', label: 'Morocco', phone: '212', taxType: 'unknown'},
  {code: 'MC', label: 'Monaco', phone: '377', taxType: 'unknown'},
  {code: 'MD', label: 'Moldova, Republic of', phone: '373', taxType: 'unknown'},
  {code: 'ME', label: 'Montenegro', phone: '382', taxType: 'unknown'},
  {code: 'MF', label: 'Saint Martin (French part)', phone: '590', taxType: 'unknown'},
  {code: 'MG', label: 'Madagascar', phone: '261', taxType: 'unknown'},
  {code: 'MH', label: 'Marshall Islands', phone: '692', taxType: 'unknown'},
  {code: 'MK', label: 'North Macedonia', phone: '389', taxType: 'unknown'},
  {code: 'ML', label: 'Mali', phone: '223', taxType: 'unknown'},
  {code: 'MM', label: 'Myanmar', phone: '95', taxType: 'unknown'},
  {code: 'MN', label: 'Mongolia', phone: '976', taxType: 'unknown'},
  {code: 'MO', label: 'Macao', phone: '853', taxType: 'unknown'},
  {code: 'MP', label: 'Northern Mariana Islands', phone: '1-670', taxType: 'unknown'},
  {code: 'MQ', label: 'Martinique', phone: '596', taxType: 'unknown'},
  {code: 'MR', label: 'Mauritania', phone: '222', taxType: 'unknown'},
  {code: 'MS', label: 'Montserrat', phone: '1-664', taxType: 'unknown'},
  {code: 'MT', label: 'Malta', phone: '356', taxType: 'eu_vat'},
  {code: 'MU', label: 'Mauritius', phone: '230', taxType: 'unknown'},
  {code: 'MV', label: 'Maldives', phone: '960', taxType: 'unknown'},
  {code: 'MW', label: 'Malawi', phone: '265', taxType: 'unknown'},
  {code: 'MX', label: 'Mexico', phone: '52', taxType: 'mx_rfc'},
  {code: 'MY', label: 'Malaysia', phone: '60', taxType: 'my_frp'},
  {code: 'MZ', label: 'Mozambique', phone: '258', taxType: 'unknown'},
  {code: 'NA', label: 'Namibia', phone: '264', taxType: 'unknown'},
  {code: 'NC', label: 'New Caledonia', phone: '687', taxType: 'unknown'},
  {code: 'NE', label: 'Niger', phone: '227', taxType: 'unknown'},
  {code: 'NF', label: 'Norfolk Island', phone: '672', taxType: 'unknown'},
  {code: 'NG', label: 'Nigeria', phone: '234', taxType: 'unknown'},
  {code: 'NI', label: 'Nicaragua', phone: '505', taxType: 'unknown'},
  {code: 'NL', label: 'Netherlands', phone: '31', taxType: 'eu_vat'},
  {code: 'NO', label: 'Norway', phone: '47', taxType: 'no_vat'},
  {code: 'NP', label: 'Nepal', phone: '977', taxType: 'unknown'},
  {code: 'NR', label: 'Nauru', phone: '674', taxType: 'unknown'},
  {code: 'NU', label: 'Niue', phone: '683', taxType: 'unknown'},
  {code: 'NZ', label: 'New Zealand', phone: '64', taxType: 'nz_gst'},
  {code: 'OM', label: 'Oman', phone: '968', taxType: 'unknown'},
  {code: 'PA', label: 'Panama', phone: '507', taxType: 'unknown'},
  {code: 'PE', label: 'Peru', phone: '51', taxType: 'pe_ruc'},
  {code: 'PF', label: 'French Polynesia', phone: '689', taxType: 'unknown'},
  {code: 'PG', label: 'Papua New Guinea', phone: '675', taxType: 'unknown'},
  {code: 'PH', label: 'Philippines', phone: '63', taxType: 'unknown'},
  {code: 'PK', label: 'Pakistan', phone: '92', taxType: 'unknown'},
  {code: 'PL', label: 'Poland', phone: '48', taxType: 'eu_vat'},
  {code: 'PM', label: 'Saint Pierre and Miquelon', phone: '508', taxType: 'unknown'},
  {code: 'PN', label: 'Pitcairn', phone: '870', taxType: 'unknown'},
  {code: 'PR', label: 'Puerto Rico', phone: '1', taxType: 'unknown'},
  {code: 'PS', label: 'Palestine, State of', phone: '970', taxType: 'unknown'},
  {code: 'PT', label: 'Portugal', phone: '351', taxType: 'eu_vat'},
  {code: 'PW', label: 'Palau', phone: '680', taxType: 'unknown'},
  {code: 'PY', label: 'Paraguay', phone: '595', taxType: 'unknown'},
  {code: 'QA', label: 'Qatar', phone: '974', taxType: 'unknown'},
  {code: 'RE', label: 'Reunion', phone: '262', taxType: 'unknown'},
  {code: 'RO', label: 'Romania', phone: '40', taxType: 'ro_cui'},
  {code: 'RS', label: 'Serbia', phone: '381', taxType: 'rs_pib'},
  {code: 'RU', label: 'Russian Federation', phone: '7', taxType: 'ru_inn'},
  {code: 'RW', label: 'Rwanda', phone: '250', taxType: 'unknown'},
  {code: 'SA', label: 'Saudi Arabia', phone: '966', taxType: 'sa_vat'},
  {code: 'SB', label: 'Solomon Islands', phone: '677', taxType: 'unknown'},
  {code: 'SC', label: 'Seychelles', phone: '248', taxType: 'unknown'},
  {code: 'SD', label: 'Sudan', phone: '249', taxType: 'unknown'},
  {code: 'SE', label: 'Sweden', phone: '46', taxType: 'eu_vat'},
  {code: 'SG', label: 'Singapore', phone: '65', taxType: 'sg_uen'},
  {code: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha', phone: '290', taxType: 'unknown'},
  {code: 'SI', label: 'Slovenia', phone: '386', taxType: 'eu_vat'},
  {code: 'SJ', label: 'Svalbard and Jan Mayen', phone: '47', taxType: 'unknown'},
  {code: 'SK', label: 'Slovakia', phone: '421', taxType: 'eu_vat'},
  {code: 'SL', label: 'Sierra Leone', phone: '232', taxType: 'unknown'},
  {code: 'SM', label: 'San Marino', phone: '378', taxType: 'unknown'},
  {code: 'SN', label: 'Senegal', phone: '221', taxType: 'unknown'},
  {code: 'SO', label: 'Somalia', phone: '252', taxType: 'unknown'},
  {code: 'SR', label: 'Suriname', phone: '597', taxType: 'unknown'},
  {code: 'SS', label: 'South Sudan', phone: '211', taxType: 'unknown'},
  {code: 'ST', label: 'Sao Tome and Principe', phone: '239', taxType: 'unknown'},
  {code: 'SV', label: 'El Salvador', phone: '503', taxType: 'sv_nit'},
  {code: 'SX', label: 'Sint Maarten (Dutch part)', phone: '1-721', taxType: 'unknown'},
  {code: 'SY', label: 'Syrian Arab Republic', phone: '963', taxType: 'unknown'},
  {code: 'SZ', label: 'Eswatini', phone: '268', taxType: 'unknown'},
  {code: 'TC', label: 'Turks and Caicos Islands', phone: '1-649', taxType: 'unknown'},
  {code: 'TD', label: 'Chad', phone: '235', taxType: 'unknown'},
  {code: 'TF', label: 'French Southern Territories', phone: '262', taxType: 'unknown'},
  {code: 'TG', label: 'Togo', phone: '228', taxType: 'unknown'},
  {code: 'TH', label: 'Thailand', phone: '66', taxType: 'th_vat'},
  {code: 'TJ', label: 'Tajikistan', phone: '992', taxType: 'unknown'},
  {code: 'TK', label: 'Tokelau', phone: '690', taxType: 'unknown'},
  {code: 'TL', label: 'Timor-Leste', phone: '670', taxType: 'unknown'},
  {code: 'TM', label: 'Turkmenistan', phone: '993', taxType: 'unknown'},
  {code: 'TN', label: 'Tunisia', phone: '216', taxType: 'unknown'},
  {code: 'TO', label: 'Tonga', phone: '676', taxType: 'unknown'},
  {code: 'TR', label: 'Turkey', phone: '90', taxType: 'tr_tin'},
  {code: 'TT', label: 'Trinidad and Tobago', phone: '1-868', taxType: 'unknown'},
  {code: 'TV', label: 'Tuvalu', phone: '688', taxType: 'unknown'},
  {code: 'TW', label: 'Taiwan, Province of China', phone: '886', taxType: 'tw_vat'},
  {code: 'TZ', label: 'Tanzania, United Republic of', phone: '255', taxType: 'unknown'},
  {code: 'UA', label: 'Ukraine', phone: '380', taxType: 'ua_vat'},
  {code: 'UG', label: 'Uganda', phone: '256', taxType: 'unknown'},
  {code: 'UM', label: 'United States Minor Outlying Islands', phone: '1', taxType: 'us_ein'},
  {code: 'US', label: 'United States', phone: '1', taxType: 'us_ein'},
  {code: 'UY', label: 'Uruguay', phone: '598', taxType: 'uy_ruc'},
  {code: 'UZ', label: 'Uzbekistan', phone: '998', taxType: 'unknown'},
  {code: 'VA', label: 'Holy See (Vatican City State)', phone: '379', taxType: 'unknown'},
  {code: 'VC', label: 'Saint Vincent and the Grenadines', phone: '1-784', taxType: 'unknown'},
  {code: 'VE', label: 'Venezuela', phone: '58', taxType: 've_rif'},
  {code: 'VG', label: 'Virgin Islands, British', phone: '1-284', taxType: 'unknown'},
  {code: 'VI', label: 'Virgin Islands, U.S.', phone: '1-340', taxType: 'unknown'},
  {code: 'VN', label: 'Vietnam', phone: '84', taxType: 'vn_tin'},
  {code: 'VU', label: 'Vanuatu', phone: '678', taxType: 'unknown'},
  {code: 'WF', label: 'Wallis and Futuna', phone: '681', taxType: 'unknown'},
  {code: 'WS', label: 'Samoa', phone: '685', taxType: 'unknown'},
  {code: 'YE', label: 'Yemen', phone: '967', taxType: 'unknown'},
  {code: 'YT', label: 'Mayotte', phone: '262', taxType: 'unknown'},
  {code: 'ZA', label: 'South Africa', phone: '27', taxType: 'za_vat'},
  {code: 'ZM', label: 'Zambia', phone: '260', taxType: 'unknown'},
  {code: 'ZW', label: 'Zimbabwe', phone: '263', taxType: 'unknown'}
];
