import { SCPaginatedResponse } from '@selfcommunity/api-services';
import { SCContributionType } from '@selfcommunity/types';


// @ts-ignore
const exampleExploreData: SCPaginatedResponse<any> = {
  count: 843,
  next: 'https://italiano.quentrix.com/api/v2/feed/explore/?limit=5&offset=25',
  previous: 'https://italiano.quentrix.com/api/v2/feed/explore/?limit=5&offset=15',
  results: [
    {
      type: SCContributionType.POST,
      post: {
        id: 1128,
        type: SCContributionType.POST,
        last_activity_at: '2022-08-08T03:55:00+02:00',
        author: {
          id: 40,
          username: 'seqiko',
          real_name: 'Ebafege Seqiko',
          avatar: 'https://www.gravatar.com/avatar/22fa0e6322cb060a37d6ce4b8025c202/?s=209&d=identicon',
          ext_id: null,
          followings_counter: 9,
          followers_counter: 9,
          posts_counter: 2,
          discussions_counter: 1,
          categories_counter: 4,
          date_joined: '2019-11-04T17:36:08.496958+01:00',
          bio: '',
          location: '',
          location_lat_lng: null,
          position_lat_lng: null,
          date_of_birth: null,
          description: '',
          gender: 'Unspecified',
          website: '',
          cover: null,
          tags: [],
          reputation: 38,
          company_name: null,
          company_role: null
        },
        added_at: '2022-08-08T07:30:00+02:00',
        html: 'Il TeleUccidiLadro 626 Beghelli',
        summary: 'Il TeleUccidiLadro 626 Beghelli',
        deleted: false,
        collapsed: false,
        comment_count: 6,
        view_count: 9,
        vote_count: 0,
        reactions_count: [],
        voted: false,
        reaction: null,
        follower_count: 0,
        followed: false,
        suspended: false,
        flag_count: 0,
        share_count: 0,
        slug: 'il-teleuccidiladro-626-beghelli',
        categories: [],
        medias: [
          {
            id: 831,
            added_at: '2022-08-08T13:13:34.215787+02:00',
            type: 'share',
            title:
              'Provvedimenti di limitazione del traffico    Il Magnifico Rettore del comune di Firenze    C O M A N D A   il DIVIETO relativo di transito nel territorio comunale, tutti i giorni, dal canto del gallo alle 20:00, alle seguenti categorie di veicoli:   ',
            description:
              'Provvedimenti di limitazione del traffico Il Sindaco del comune di Bologna O R D I N A il DIVIETO di transito nel territorio provinciale, ogni primo Lunedi&#x27; della settimana, dall&#x27;a ...',
            url: 'https://italiano.quentrix.com/thread/607/provvedimenti-di-limitazione-del-traffico-il-magnifico-rettore-del-comune-di-firenze-c-o-m-a-n-d-a-il-divieto-relativo-di-transito-nel-territorio/',
            image: null,
            image_width: null,
            image_height: null,
            order: null,
            embed: {
              id: 312,
              embed_type: 'sc_shared_object',
              embed_id: '607',
              url: '/thread/607/provvedimenti-di-limitazione-del-traffico-il-magnifico-rettore-del-comune-di-firenze-c-o-m-a-n-d-a-il-divieto-relativo-di-transito-nel-territorio/',
              metadata: {id: 607, type: SCContributionType.DISCUSSION}
            }
          }
        ],
        location: null,
        addressing: [],
        poll: null
      },
      seen_by_id: [40, 7, 1],
      has_boost: false
    },
    {
      type: SCContributionType.DISCUSSION,
      discussion: {
        id: 1140,
        type: SCContributionType.DISCUSSION,
        last_activity_at: '2022-08-08T18:11:00+02:00',
        author: {
          id: 345,
          username: 'qekaluyox',
          real_name: 'Oyeqarad Qekaluyox',
          avatar: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/avatars/345/resized/209/209/a2555c826ebfbe367cc502189829d724.png',
          ext_id: null,
          followings_counter: 10,
          followers_counter: 3,
          status: 'approved',
          posts_counter: 1,
          discussions_counter: 5,
          categories_counter: 12,
          date_joined: '2022-07-28T23:26:00+02:00',
          bio: '',
          location: '',
          location_lat_lng: null,
          position_lat_lng: null,
          date_of_birth: '1947-04-23',
          description: '',
          gender: 'Unspecified',
          website: '',
          cover: null,
          tags: [],
          reputation: 26,
          company_name: null,
          company_role: null
        },
        added_at: '2022-08-08T13:49:00+02:00',
        html: "Rinomati sociologi pensano che la pace ha legalizzato pur essendo condivisibile nelle direttrici generali. Tuttavia il desiderio di ingoio rappresenta un'altra forma di possessione maschile. Ritengo che sicuramente non mi aspetto una pietra o un gas che ragionano..",
        summary:
          'Rinomati sociologi pensano che la pace ha legalizzato pur essendo condivisibile nelle direttrici generali. Tuttavia il desiderio di ingoio rappresenta un&#x27;altra forma di possessione ...',
        deleted: false,
        collapsed: false,
        comment_count: 4,
        view_count: 8,
        vote_count: 0,
        reactions_count: [],
        voted: false,
        reaction: null,
        follower_count: 0,
        followed: false,
        suspended: false,
        flag_count: 0,
        share_count: 0,
        slug: 'socioterapeuti-dicono-che-lx27italia-ha-inglobato-secondo-unx27analisi-storica-con-tanto-di-bibliografia-sennox27-ha-a-che-fare-con-le-pellicce',
        categories: [
          {
            id: 8,
            tags: [],
            followed: false,
            order: 0,
            name: 'snby3s46j',
            name_synonyms: '',
            slug: 'vertical',
            slogan: '',
            html_info: null,
            seo_title: '',
            seo_description: '',
            auto_follow: 'none',
            active: true,
            image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/original/vertical_5128.jpeg',
            image_bigger: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/bigger/vertical_1325.jpg',
            image_big: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/big/vertical_8774.jpg',
            image_medium: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/medium/vertical_3514.jpg',
            image_small: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/small/vertical_3773.jpg',
            emotional_image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/e_original/vertical_5306.jpeg',
            emotional_image_position: 50,
            lastmod_datetime: '2021-12-21T11:06:19.767539+01:00',
            stream_order_by: 'recent',
            followers_counter: 131
          },
          {
            id: 23,
            tags: [],
            followed: true,
            order: 0,
            name: 'Ventunesimo',
            name_synonyms: '',
            slug: 'ventunesimo',
            slogan: '',
            html_info: null,
            seo_title: '',
            seo_description: '',
            auto_follow: 'none',
            active: true,
            image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/original/ventunesimo_0696.png',
            image_bigger: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/bigger/ventunesimo_2884.png',
            image_big: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/big/ventunesimo_3562.png',
            image_medium: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/medium/ventunesimo_5780.png',
            image_small: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/small/ventunesimo_1779.png',
            emotional_image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/e_original/ventunesimo_5194.jpg',
            emotional_image_position: 50,
            lastmod_datetime: '2022-03-16T11:30:13.401029+01:00',
            stream_order_by: 'recent',
            followers_counter: 109
          }
        ],
        medias: [],
        location: null,
        addressing: [],
        poll: null,
        title:
          "Socioterapeuti dicono che l'Italia ha inglobato secondo un'analisi storica con tanto di bibliografia. Senno' ha a che fare con le pellicce, ovviamente. Ritengo che vedere cio' che si semina.."
      },
      seen_by_id: [345, 299, 7, 54, 1],
      has_boost: false
    },
    {
      type: SCContributionType.DISCUSSION,
      discussion: {
        id: 1113,
        type: SCContributionType.DISCUSSION,
        last_activity_at: '2022-08-08T01:06:00+02:00',
        author: {
          id: 370,
          username: 'anixotifey',
          real_name: 'Ijuperanul Anixotifey',
          avatar: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/avatars/370/resized/209/209/ab230ec47588c7d2fa8a078d48419813.png',
          ext_id: null,
          followings_counter: 4,
          status: 'approved',
          followers_counter: 1,
          posts_counter: 0,
          discussions_counter: 2,
          categories_counter: 10,
          date_joined: '2022-08-03T22:36:00+02:00',
          bio: '',
          location: '',
          location_lat_lng: null,
          position_lat_lng: null,
          date_of_birth: null,
          description: '',
          gender: 'Female',
          website: '',
          cover: null,
          tags: [],
          reputation: 13,
          company_name: null,
          company_role: null
        },
        added_at: '2022-08-07T22:35:00+02:00',
        html: "Ciao belli... mo ve ricconto l'urtima... 'na cambogia!\n\nIeri mentre che io corevo a dducento, ma de ppiu'! Su 'a tiburtina co'a machina de mi'fratello... aho'... nun so' annato a sbatte co er Faina???!!\n\nE io allora je dico \"Vie'qqua' che te mischio come 'n mazzo de carte! Te metto 'n dito 'n bocca, uno ar culo e te sciaqquo come 'na damiggiana!\"\n\nAho'... ha sgranato j'occhi e s'e' cacato 'n mano!\n\nHa detto 'na cosa tipo \"Ma va a mori' ammazzato...\" (eh eh, e che nun lo so che era la paura a fallo parla', 'sto cojone...) poi se l'e' squajata... e' ripartito a tutta sgommella, tipo da zero a cento in ddu secondi!\n\nNzomma so' troppo bullo... so' er mejo!\n\nVabbe' ve saluto che me ne devo anna'...\n\nS'arisdraiamo...",
        summary:
          'Ciao belli... mo ve ricconto l&#x27;urtima... &#x27;na cambogia! Ieri mentre che io corevo a dducento, ma de ppiu&#x27;! Su &#x27;a tiburtina co&#x27;a machina de mi&#x27;fratello... aho&#x27;... nun so&#x27; annato a sb ...',
        deleted: false,
        collapsed: false,
        comment_count: 2,
        view_count: 8,
        vote_count: 0,
        reactions_count: [],
        voted: false,
        reaction: null,
        follower_count: 0,
        followed: false,
        suspended: false,
        flag_count: 0,
        share_count: 0,
        slug: 'prima-mentre-che-io-facevo-le-derapate-popo-a-sfonnax27-x27a-bariera-der-sono-cox27a-machina-de-mix27fratello-su-x27a-prenestina-ahox27-ax27n-certo',
        categories: [
          {
            id: 1,
            tags: [],
            followed: true,
            order: 0,
            name: 'Primo',
            name_synonyms: '',
            slug: 'primo',
            slogan: 'Test slogan',
            html_info: '',
            seo_title: 'aaa',
            seo_description: '',
            auto_follow: 'none',
            active: true,
            image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/original/primo_7527.jpeg',
            image_bigger: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/bigger/primo_0544.jpg',
            image_big: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/big/primo_8727.jpg',
            image_medium: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/medium/primo_1977.jpg',
            image_small: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/small/primo_4281.jpg',
            emotional_image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/e_original/primo_5912.jpeg',
            emotional_image_position: 0,
            lastmod_datetime: '2019-11-04T17:25:17.707380+01:00',
            stream_order_by: 'recent',
            followers_counter: 177
          },
          {
            id: 2,
            tags: [],
            followed: true,
            order: 3,
            name: 'Secondo',
            name_synonyms: '',
            slug: 'secondo',
            slogan: '',
            html_info: '',
            seo_title: '',
            seo_description: '',
            auto_follow: 'None',
            active: true,
            image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/original/secondo_3447.png',
            image_bigger: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/bigger/secondo_8627.png',
            image_big: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/big/secondo_8137.png',
            image_medium: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/medium/secondo_9174.png',
            image_small: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/small/secondo_6296.png',
            emotional_image_original: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/categories/e_original/secondo_7107.jpg',
            emotional_image_position: 50,
            lastmod_datetime: '2019-11-04T17:25:19.804779+01:00',
            stream_order_by: 'recent',
            followers_counter: 178
          }
        ],
        medias: [
          {
            id: 821,
            added_at: '2022-08-08T13:12:03.452023+02:00',
            type: 'embed',
            title: null,
            description: null,
            url: null,
            image: null,
            image_width: null,
            image_height: null,
            order: null,
            embed: {
              id: 303,
              embed_type: 'game',
              embed_id: 'ISBN-85-96-58364-0',
              url: null,
              metadata: {
                isbn: 'ISBN-85-96-58364-0',
                type: 'game',
                authors: ['Koyoharu Gotouge', 'Jane Austen'],
                product: "Aho' ciao... sapete che m'e' successo???!"
              }
            }
          }
        ],
        location: null,
        addressing: [],
        poll: null,
        title:
          "Prima, mentre che io facevo le derapate, popo a sfonna' 'a bariera der sono, co'a machina de mi'fratello su 'a prenestina... aho'... a'n certo punto... nun te vado a sbatte co er Siringa???!! Ve dico... 'na grezza da paura!  E allora je strillo \"Vie'"
      },
      seen_by_id: [370, 371, 111, 54, 7, 9],
      has_boost: false
    },
    {
      type: SCContributionType.DISCUSSION,
      discussion: {
        id: 1126,
        type: SCContributionType.DISCUSSION,
        last_activity_at: '2022-08-07T23:58:00+02:00',
        author: {
          id: 80,
          username: 'overeve',
          real_name: 'Erupo Overeve',
          avatar: 'https://www.gravatar.com/avatar/e1f5f91521749b39af9a021f79efff70/?s=209&d=identicon',
          ext_id: null,
          followings_counter: 19,
          status: 'approved',
          followers_counter: 13,
          posts_counter: 5,
          discussions_counter: 4,
          categories_counter: 3,
          date_joined: '2019-11-04T17:36:29.531449+01:00',
          bio: '',
          location: '',
          location_lat_lng: null,
          position_lat_lng: null,
          date_of_birth: null,
          description: '',
          gender: 'Unspecified',
          website: '',
          cover: null,
          tags: [],
          reputation: 158,
          company_name: null,
          company_role: null
        },
        added_at: '2022-08-07T02:24:00+02:00',
        html: 'Un pomeriggio il poeta Daiju si rec\u00f2 presso Hogen e gli chiese di mostrargli il percorso pi\u00f9 breve per ottenere il Satori.\nIl maestro indic\u00f2 una preziosa giara e disse: "Se vuoi divenire saggio devi riuscire a comprendere la buddha-natura di ogni cosa: prendi quell\'oggetto con te e medita per due anni, poi torna da me". \nQuando Daiju torn\u00f2, Hogen gli disse: "Non sei ancora pronto: medita per altri tre anni, poi torna da me".\nQuando il giovane allievo fece ritorno, il maestro disse: "Wasabi, Mishima, Boutique!", e a quelle parole Daiju fu illuminato!',
        summary:
          'Un pomeriggio il poeta Daiju si rec\u00f2 presso Hogen e gli chiese di mostrargli il percorso pi\u00f9 breve per ottenere il Satori. Il maestro indic\u00f2 una preziosa giara e disse: &quot;Se vuoi di ...',
        deleted: false,
        collapsed: false,
        comment_count: 5,
        view_count: 7,
        vote_count: 0,
        reactions_count: [],
        voted: false,
        reaction: null,
        follower_count: 0,
        followed: false,
        suspended: false,
        flag_count: 0,
        share_count: 0,
        slug: 'un-mattino-px27an-shan-fece-visita-a-seng-tsx27an-e-lo-prego-di-mostrargli-la-strada-piu-facile-per-conseguire-lx27illuminazione-il-maestro-indico-una',
        categories: [],
        medias: [
          {
            id: 829,
            added_at: '2022-08-08T13:12:31.141196+02:00',
            type: 'embed',
            title: null,
            description: null,
            url: null,
            image: null,
            image_width: null,
            image_height: null,
            order: null,
            embed: {
              id: 310,
              embed_type: 'cd',
              embed_id: 'ISBN-32-65-23242-0',
              url: null,
              metadata: {
                isbn: 'ISBN-32-65-23242-0',
                type: 'cd',
                authors: ['Zerocalcare', 'Luis Sep\u00falveda'],
                product: 'Un pomeriggio il guerriero'
              }
            }
          }
        ],
        location: null,
        addressing: [],
        poll: null,
        title:
          "Un mattino P'an-shan fece visita a Seng-ts'an e lo preg\u00f2 di mostrargli la strada pi\u00f9 facile per conseguire l'illuminazione. Il maestro indic\u00f2 una consunta statua di platino e disse: \"Se davvero desideri diventare saggio devi riuscire a comprendere la"
      },
      seen_by_id: [80, 381, 7],
      has_boost: false
    },
    {
      type: SCContributionType.POST,
      post: {
        id: 1116,
        type: SCContributionType.POST,
        last_activity_at: '2022-08-07T22:25:00+02:00',
        author: {
          id: 248,
          username: 'quhasisal',
          real_name: 'Nejocufu Quhasisal',
          avatar: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/avatars/248/resized/209/209/e3087379702f91d90afb015100062b9d.png',
          ext_id: null,
          followings_counter: 10,
          status: 'approved',
          followers_counter: 3,
          posts_counter: 1,
          discussions_counter: 0,
          categories_counter: 15,
          date_joined: '2022-07-16T00:34:00+02:00',
          bio: '',
          location: '',
          location_lat_lng: null,
          position_lat_lng: null,
          date_of_birth: '1976-08-27',
          description: '',
          gender: 'Unspecified',
          website: '',
          cover: null,
          tags: [],
          reputation: 21,
          company_name: null,
          company_role: null
        },
        added_at: '2022-08-07T04:20:00+02:00',
        html: '...la 18\u00ba Abbuffata agonistica del nero sotto le unghie dei maiali di SAN CARETTO (EN)',
        summary: '...la 18\u00ba Abbuffata agonistica del nero sotto le unghie dei maiali di SAN CARETTO (EN)',
        deleted: false,
        collapsed: false,
        comment_count: 1,
        view_count: 3,
        vote_count: 1,
        reactions_count: [
          {
            reaction: {
              id: 3,
              label: 'Finger',
              image: 'https://static.quentrix.com/dhpyt711mb8h2n3m/upfiles/reactions/selection-tool.svg',
              sentiment: 2,
              active: true
            },
            count: 1
          }
        ],
        voted: false,
        reaction: null,
        follower_count: 0,
        followed: false,
        suspended: false,
        flag_count: 0,
        share_count: 0,
        slug: 'la-18o-abbuffata-agonistica-del-nero-sotto-le-unghie-dei-maiali-di-san-caretto-en',
        categories: [],
        medias: [
          {
            id: 823,
            added_at: '2022-08-08T13:12:09.200866+02:00',
            type: 'embed',
            title: null,
            description: null,
            url: null,
            image: null,
            image_width: null,
            image_height: null,
            order: null,
            embed: {
              id: 305,
              embed_type: 'game',
              embed_id: 'ISBN-52-64-04336-0',
              url: null,
              metadata: {
                isbn: 'ISBN-52-64-04336-0',
                type: 'game',
                authors: ['Akira Toriyama', 'Sophie Kinsella', 'Virginia Woolf'],
                product: '...la 11\u00ba Battaglia delle'
              }
            }
          }
        ],
        location: null,
        addressing: [],
        poll: null
      },
      seen_by_id: [248, 7],
      has_boost: false
    }
  ]
};
export {exampleExploreData};
