import UserConnectionsRequestsSentWidget, {UserConnectionsRequestsSentWidgetProps} from './UserConnectionsRequestsSentWidget';
import UserConnectionsRequestsSentWidgetSkeleton from './Skeleton';
export default UserConnectionsRequestsSentWidget;
export {UserConnectionsRequestsSentWidgetProps, UserConnectionsRequestsSentWidgetSkeleton};
