# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - prerelease

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: yarn bootstrap
    - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git config --global user.email "fede.torre@gmail.com"
    - run: git config --global user.name "fedetorre"
    - run: yarn build
    - run: yarn prerelease
    - name: Open pull-request (prerelease -> main)
      uses: mirk8xr/pull-request@v2.6.2
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} from prerelease into main"
        pr_body: "👑 *An automated PR*"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get @selfcommunity/types version
      id: types
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/types
    - run: echo "@selfcommunity/types - ${{ steps.types.outputs.current-version }}"
    - name: Get @selfcommunity/react-i18n version
      id: react-i18n
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-i18n
    - run: echo "@selfcommunity/react-i18n - ${{ steps.react-i18n.outputs.current-version }}"
    - name: Get @selfcommunity/react-core version
      id: core
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-core
    - run: echo "@selfcommunity/react-core - ${{ steps.react-core.outputs.current-version }}"
    - name: Get @selfcommunity/react-ui version
      id: ui
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-ui
    - run: echo "@selfcommunity/react-ui - ${{ steps.react-ui.outputs.current-version }}"
    - name: Get @selfcommunity/react-templates version
      id: templates
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-templates
    - run: echo "@selfcommunity/react-templates - ${{ steps.react-templates.outputs.current-version }}"
    - uses: peter-evans/repository-dispatch@v1
      name: Repository Dispatch
      with:
        token: ${{ secrets.DOCS_ACCESS_TOKEN }}
        repository: selfcommunity/developers-doc
        event-type: community-js-prerelease
        client-payload: '{"react-i18n": "${{ steps.react-i18n.outputs.current-version }}", "react-core": "${{ steps.react-core.outputs.current-version }}", "react-ui": "${{ steps.react-ui.outputs.current-version }}", "react-templates": "${{ steps.react-templates.outputs.current-version }}"}'
