# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - prerelease

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: yarn bootstrap
    - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git config --global user.email "fede.torre@gmail.com"
    - run: git config --global user.name "fedetorre"
    - run: yarn build
    - run: yarn prerelease
    - name: Open pull-request
      uses: repo-sync/pull-request@v2
      with:
        entrypoint: './.github/pull-request/entrypoint.sh'
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} from prerelease into main"
        pr_body: "👑 *An automated PR*"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get @selfcommunity/i18n version
      id: i18n
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/sc-i18n
    - run: echo "@selfcommunity/i18n - ${{ steps.i18n.outputs.current-version }}"
    - name: Get @selfcommunity/core version
      id: core
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/sc-core
    - run: echo "@selfcommunity/core - ${{ steps.core.outputs.current-version }}"
    - name: Get @selfcommunity/ui version
      id: ui
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/sc-ui
    - run: echo "@selfcommunity/ui - ${{ steps.ui.outputs.current-version }}"
    - name: Get @selfcommunity/templates version
      id: templates
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/sc-templates
    - run: echo "@selfcommunity/templates - ${{ steps.templates.outputs.current-version }}"
    - uses: peter-evans/repository-dispatch@v1
      name: Repository Dispatch
      with:
        token: ${{ secrets.DOCS_ACCESS_TOKEN }}
        repository: selfcommunity/developers-doc
        event-type: community-ui-prerelease
        client-payload: '{"i18n": "${{ steps.i18n.outputs.current-version }}", "core": "${{ steps.core.outputs.current-version }}", "ui": "${{ steps.ui.outputs.current-version }}", "templates": "${{ steps.templates.outputs.current-version }}"}'
