# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: yarn bootstrap
    - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git config --global user.email "team@quentral.com"
    - run: git config --global user.name "quentralhub"
    - run: yarn build
    - run: yarn release
    - name: Open pull-request (main -> prerelease)
      uses: mirk8xr/pull-request@v2.6.2
      with:
        destination_branch: "prerelease"
        pr_title: "[skip actions] Pulling ${{ github.ref }} from main into prerelease"
        pr_body: "👑 *An automated PR* skipping request"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get @selfcommunity/types version
      id: types
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/types
    - run: echo "@selfcommunity/types - ${{ steps.types.outputs.current-version }}"
    - name: Get @selfcommunity/utils version
      id: utils
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/utils
    - run: echo "@selfcommunity/utils - ${{ steps.utils.outputs.current-version }}"
    - name: Get @selfcommunity/api-services version
      id: api-services
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/api-services
    - run: echo "@selfcommunity/api-services - ${{ steps.api-services.outputs.current-version }}"
    - name: Get @selfcommunity/react-i18n version
      id: react-i18n
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-i18n
    - run: echo "@selfcommunity/react-i18n - ${{ steps.react-i18n.outputs.current-version }}"
    - name: Get @selfcommunity/react-core version
      id: react-core
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-core
    - run: echo "@selfcommunity/react-core - ${{ steps.react-core.outputs.current-version }}"
    - name: Get @selfcommunity/react-ui version
      id: react-ui
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-ui
    - run: echo "@selfcommunity/react-ui - ${{ steps.react-ui.outputs.current-version }}"
    - name: Get @selfcommunity/react-templates version
      id: react-templates
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-templates
    - run: echo "@selfcommunity/react-templates - ${{ steps.react-templates.outputs.current-version }}"
    - name: Get @selfcommunity/react-theme-default version
      id: react-theme-default
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: packages/react-theme-default
    - run: echo "@selfcommunity/react-theme-default - ${{ steps.react-theme-default.outputs.current-version }}"
    - uses: peter-evans/repository-dispatch@v2
      name: Repository Dispatch
      with:
        token: ${{ secrets.DOCS_ACCESS_TOKEN }}
        repository: selfcommunity/developers-doc
        event-type: community-js-release
        client-payload: '{"types": "${{ steps.types.outputs.current-version }}", "utils": "${{ steps.utils.outputs.current-version }}", "react-i18n": "${{ steps.react-i18n.outputs.current-version }}", "react-core": "${{ steps.react-core.outputs.current-version }}", "react-ui": "${{ steps.react-ui.outputs.current-version }}", "react-templates": "${{ steps.react-templates.outputs.current-version }}"}'

