export const COMPOSER_TYPE_DISCUSSION = 'discussion';
export const COMPOSER_TYPE_POST = 'post';
export const COMPOSER_TYPES = {
  [COMPOSER_TYPE_DISCUSSION]: COMPOSER_TYPE_DISCUSSION,
  [COMPOSER_TYPE_POST]: COMPOSER_TYPE_POST
};

export const COMPOSER_TITLE_MAX_LENGTH = 160;
