const REPORT_SPAM = 0;
const REPORT_AGGRESSIVE = 1;
const REPORT_VULGAR = 2;
const REPORT_POORCONTENT = 3;
const REPORT_OFFTOPIC = 4;

const REPORTS = [REPORT_SPAM, REPORT_AGGRESSIVE, REPORT_VULGAR, REPORT_POORCONTENT, REPORT_OFFTOPIC];

/** Export all types of flag **/
export {REPORT_SPAM, REPORT_AGGRESSIVE, REPORT_VULGAR, REPORT_POORCONTENT, REPORT_OFFTOPIC, REPORTS};

/** Moderation actions **/
export const MODERATION_CONTRIBUTION_STATE_HIDDEN = 'hidden';
export const MODERATION_CONTRIBUTION_STATE_DELETED = 'deleted';

/** Moderation actions **/
export const MODERATION_TYPE_ACTION_HIDE = 'hide';
export const MODERATION_TYPE_ACTION_DELETE = 'delete';
